<img src="image/numpy.jpg">

In [3]:
# 리스트의 확장판(데이터연산, 통계분석), numpy 확장판 pandas
import numpy as np

## 용어정리

scalar : 상수값 (10,3.14, 'korea')
vactor (1차원) : [10,20,30]
matrix (2차원) : [[10,20,30],[100,200,300]] 2x3 (2행 3열)
3차원  [[[10,20,30],[100,200,300]], [[10,20,30],[100,200,300]]] 2x2x3 

1. ndarray 생성방법

In [5]:
arr1 = np.array([10,20,30])
print(type(arr1))
print(arr1)
arr1

<class 'numpy.ndarray'>
[10 20 30]


array([10, 20, 30])

In [6]:
arr2= np.array([[10,20,30],[100,200,300]])
print(arr2)
arr2

[[ 10  20  30]
 [100 200 300]]


array([[ 10,  20,  30],
       [100, 200, 300]])

2. ndarray 생성방법

In [10]:
arr3 = np.arange(1,11,1) # 1 <= arr3 <11 1씩증가
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr4 = np.arange(1,11,2) # 1 <= arr3 <11 2씩증가
arr4

array([1, 3, 5, 7, 9])

3. ndarray 생성방법 (랜덤)

In [26]:
arr5 = np.random.randint(1,11, size=5)
arr5

array([9, 6, 9, 7, 6])

In [31]:
arr6 = np.random.randint(1,11, size=(3,2))
arr6

array([[ 2,  1],
       [ 5,  9],
       [10,  7]])

In [32]:
# 0 ~ 1 사이 실수값 반환
np.random.rand(5)

array([0.23984909, 0.0575857 , 0.33012495, 0.07678167, 0.17891703])

In [33]:
np.random.rand(2,3)

array([[0.08684095, 0.58890626, 0.98373061],
       [0.63508899, 0.01577973, 0.64277752]])

In [36]:
# 표준정규분포 (평균이 0 편차는 1에 가깝게함) 갯수가 많을수록
np.random.randn(5)

array([ 0.54757001, -1.19819866,  0.79138624,  0.6102484 ,  0.721114  ])

In [39]:
np.random.choice([1,2,3,4,5], size=3)

array([2, 3, 3])

In [60]:
np.random.choice(np.arange(1,6), size=3, replace=False)

array([1, 3, 2])

In [64]:
arr7 = np.arange(1,10)
print(arr7)
np.random.shuffle(arr7)
arr7

[1 2 3 4 5 6 7 8 9]


array([6, 3, 8, 9, 7, 4, 2, 1, 5])

4. ndarray 생성방법 

In [66]:
arr8 = np.int32([1,2,3,4,5])
# np.aray([1,2,3,4,5], dtype=np.int32)
arr8

array([1, 2, 3, 4, 5])

In [67]:
np.int64([1,2,3,4,5])

array([1, 2, 3, 4, 5], dtype=int64)

In [68]:
np.float32([1,2,3,4,5])

array([1., 2., 3., 4., 5.], dtype=float32)

In [72]:
np.array([1,2,3,4,5], dtype=np.str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [74]:
# 1로만 구성되어있는 n배열
np.ones(3)

array([1., 1., 1.])

In [75]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.zeros(3)

array([0., 0., 0.])

In [78]:
# sparse (희소행렬) one hot encoding
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.linspace(1, 10 )

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [82]:
# 1부터 10까지 동일한 간격으로 5개 생성 linespace
np.linspace(1,10,5 )

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [88]:
# 중복제거
value, count = np.unique( [1,2,2,3,3,4,4,5], return_counts=True)
print(value)
print(count)

[1 2 3 4 5]
[1 2 2 2 1]


In [89]:
for a,b in zip(value, count):
    print(a,b)

1 1
2 2
3 2
4 2
5 1
