In [1]:
import numpy as np

In [2]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [3]:
arr.dtype

dtype('int32')

In [5]:
# 배열에 속해있는 데이터 갯수
arr.size

5

In [6]:
# 몇행 몇열인지 추출
arr.shape

(5,)

In [8]:
# 몇차원인지 확인
arr.ndim

1

In [12]:
arr1 = np.array([[11,22],[33,44],[55,66]])
arr1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [13]:
arr1.shape

(3, 2)

In [16]:
arr1.ndim

2

In [14]:
arr1.size

6

In [15]:
# 역변환 시킴 (3행 2열을 2행 3열 구조로)
arr1.T

array([[11, 33, 55],
       [22, 44, 66]])

### 형변환

In [17]:
arr.dtype

dtype('int32')

In [21]:
# 데이터 타입 변경, 적용할려면 새로운 변수에 받아야함
arr_int = arr.astype(np.int64)

In [22]:
print(arr.dtype)
print(arr_int.dtype)

int32
int64


### 벡터를 매트릭스로 변환

In [23]:
arr2 = np.array([1,2,3,4,5,6])
arr2

array([1, 2, 3, 4, 5, 6])

In [24]:
# 적용하려면 새로운 변수에 저장
arr2.reshape( 3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
# -1은 값에 맞게 알아서 결정
arr2.reshape( -1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2_1 = arr2.reshape( 2,-1)
arr2_1

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2_1.size

6