In [1]:
import numpy as np

In [2]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

ndarray 객체의 멤버함수 + np의 함수 <br>
np의 함수

In [3]:
arr.sum()

165

In [4]:
np.sum(arr)

165

In [5]:
arr.mean()

33.0

In [6]:
np.mean(arr)

33.0

In [8]:
# 가장 큰값의 인덱스
# np.argmax(arr)
arr.argmax()

4

In [10]:
# 가장 작은 값의 인덱스
arr.argmin()

0

In [12]:
# 표준편차 (개별 데이터를 평균값으로 뺀 후 ...)
arr.std()
np.std(arr)

15.556349186104045

In [14]:
# 데이터를 정렬 했을 때 가운데 값
np.median(arr)

33.0

In [15]:
arr1 = np.array([11,22,33,44,55,66])
arr1

array([11, 22, 33, 44, 55, 66])

In [16]:
# 가운데 값이 2개인 경우 2개를 합한후 2로 나눈값이 출력
np.median(arr1)

38.5

In [18]:
# 데이터를 정렬했을때 50%에 해당하는 값
np.quantile(arr,0.5)

33.0

In [22]:
# 각각에 해당하는 값을 출력
np.quantile(arr,[0.25, 0.5, 0.75])

array([22., 33., 44.])

In [23]:
# quantile과는 단위차이
np.percentile(arr,[25,50,75])

array([22., 33., 44.])

## 연습문제

In [49]:
kor = np.array( [60,55,70,30,20,90])
kor

array([60, 55, 70, 30, 20, 90])

In [25]:
# 1. 국어점수가 가장 큰 값을 구하시요
np.max(kor)

90

In [27]:
# 2. 국어점수가 80점 이상인 값을 구하시오
kor[kor>=80]

array([90])

In [ ]:
# 3. 국어점수가 50점이상 80이하인 값을 구하시요
# 4. 국어점수의 평균을 구하시요.
# 5. 국어점수의 총합을 구하시요.
# 6. 국어점수가 40점이하인 데이터를 삭제하시요
# 7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하시요.
# 8. 국어점수 top5를 구하시요
# 9. 국어점수가 70점이상이면 '합격', 아니면 '불합격' 으로
# 아래와 같이 출력하시요

# 60 '불합격'
# 55 '불합격'


In [29]:
# 3. 국어점수가 50점이상 80이하인 값을 구하시요
kor[(kor>=50) & (kor<=80)]

array([60, 55, 70])

In [35]:
# 4. 국어점수의 평균을 구하시요.
np.mean(kor)

54.166666666666664

In [36]:
# 5. 국어점수의 총합을 구하시요.
np.sum(kor)

325

In [44]:
# 6. 국어점수가 40점이하인 데이터를 삭제하시요
kor_de = np.delete(kor,kor <= 40)
kor_de

array([60, 55, 70, 90])

In [50]:
kor

array([60, 55, 70, 30, 20, 90])

In [51]:
# 7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하시요.
kor[kor >= 50] = kor[kor >= 50]*1.1
kor

array([66, 60, 77, 30, 20, 99])

In [57]:
# 8. 국어점수 top5를 구하시요
kor2 = np.sort(kor)[-1:-6:-1]
kor2

array([99, 77, 66, 60, 30])

In [56]:
# 9. 국어점수가 70점이상이면 '합격', 아니면 '불합격' 으로
np.where(kor>=70,'합격','불합격')
for s,r in zip(kor,np.where(kor>=70,'합격','불합격')):
    print(s,r)

66 불합격
60 불합격
77 합격
30 불합격
20 불합격
99 합격
