In [1]:
import numpy as np

In [67]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [3]:
data.shape

(4, 3)

In [116]:
# 3차원으로 변경
# (2차원 데이터 갯수 (-1), 행, 열)
data.reshape(-1,3,2)

array([[[ 1,  2],
        [ 3,  7],
        [ 5,  2]],

       [[10,  1],
        [ 8,  6],
        [ 3,  4]]])

## 2차원 데이터 인덱싱, 슬라이싱

In [9]:
# [행, 열] : 2차원
# [면, 행, 열] :

In [11]:
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [119]:
# 2행의 값 [1]
data[1]

array([7, 5, 2])

In [122]:
# 2행 2열의 값 [1,1]
data[1,1]

5

In [120]:
# 1행, 3행, 4행 출력
data[[0,2,3]]

array([[ 1,  2,  3],
       [10,  1,  8],
       [ 6,  3,  4]])

In [15]:
data[1:3]

array([[ 7,  5,  2],
       [10,  1,  8]])

In [16]:
# 2행, 4행 값을 출력하고 2열부터의 값을 출력
data[1:3,1:]

array([[5, 2],
       [1, 8]])

In [33]:
# 행은 2행부터 끝까지, 열의 값은 1열과 3열의 값 출력
data[1:,[0,2]]

array([[ 7,  2],
       [10,  8],
       [ 6,  4]])

In [22]:
# 마지막 열을 제외하고 선택하시오
# 특성 데이터 추출시 많이 활용
data[:,:-1]

array([[ 1,  2],
       [ 7,  5],
       [10,  1],
       [ 6,  3]])

In [29]:
# 마지막 열만 선택하시오
data[:,-1:]
data[:,[-1]]

array([[3],
       [2],
       [8],
       [4]])

## 2차원데이터 boolean index(행단위)

In [35]:
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [34]:
data[[True, True, False, False]]

array([[1, 2, 3],
       [7, 5, 2]])

## 2차원 연산

In [50]:
data

array([[ 1,  7,  3],
       [ 9,  8,  4],
       [10, 12,  8],
       [ 6,  8,  4]])

In [52]:
data + 2

array([[ 3,  4,  5],
       [ 9,  7,  4],
       [12,  3, 10],
       [ 8,  5,  6]])

In [62]:
data[1] = data[1] + 2

In [61]:
data[:,1]+2

array([4, 7, 3, 5])

In [54]:
data[:,1]=data[:,1]+2

In [59]:
data[:,0] > 5

array([False,  True,  True,  True])

In [60]:
# True에 해당하는 행을 출력
data[data[:,0] > 5]

array([[ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [66]:
(data[:,1]>=3) & (data[:,1]<=5)

array([False,  True, False,  True])

In [65]:
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

## 2차원 추가, 수정, 삭제, 검색, 정렬

In [68]:
ax = np.array( [[1,2],[3,4]])
ay = np.array( [[5,6],[7,8]])

In [73]:
# 2차원이 풀어져서 입력
np.append(ax, ay, axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
# 2차원 구조로 추가
# row에 추가
np.append(ax, ay, axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [75]:
# column에 추가
np.append(ax, ay, axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [76]:
# 열단위로 추가
np.hstack((ax, ay))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [78]:
# 행단위로 추가
np.vstack((ax,ay))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### 삭제

In [89]:
# 삭제
# 해당 행이 삭제
# 0행, 2행이 삭제
np.delete(data, [0,2], axis=0)

array([[7, 5, 2],
       [6, 3, 4]])

In [90]:

# 1행의 0,2 인덱스 값 삭제
np.delete(data, [0,2])

array([ 2,  7,  5,  2, 10,  1,  8,  6,  3,  4])

In [91]:
# 해당 컬럼이 삭제
np.delete(data, [0,2], axis=1)

array([[2],
       [5],
       [1],
       [3]])

In [88]:
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

### 정렬

In [93]:
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [95]:
# 1차원으로 정렬
np.sort(data, axis=None)

array([ 1,  1,  2,  2,  3,  3,  4,  5,  6,  7,  8, 10])

In [96]:
# 컬렴 단위로 정렬
np.sort(data, axis=0)

array([[ 1,  1,  2],
       [ 6,  2,  3],
       [ 7,  3,  4],
       [10,  5,  8]])

In [99]:
# 행단위로 정렬
np.sort(data, axis=1)

array([[ 1,  2,  3],
       [ 2,  5,  7],
       [ 1,  8, 10],
       [ 3,  4,  6]])

## 2차원 통계

2차원 통계<br>
디폴트 axis = None ==> 1차원 통계<br>
axis = 0         == > 컬럼별 통계값<br>
axis = 1         == > 행별 통계값

In [103]:
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [104]:
# 컬럼별 통계값
np.sum(data, axis=0)

array([24, 11, 17])

In [105]:
# 로우별 통계값
np.sum(data, axis=1)

array([ 6, 14, 19, 13])

In [106]:
np.mean(data, axis=0)

array([6.  , 2.75, 4.25])

In [107]:
np.mean(data, axis=1)

array([2.        , 4.66666667, 6.33333333, 4.33333333])

In [108]:
# 1차원에서 가장 큰값
np.max(data, axis=None)

10

In [109]:
np.max(data, axis=0)

array([10,  5,  8])

In [110]:
np.argmax(data, axis=None)

6

In [111]:
# 컬럼에서 가장 큰 값의 인덱스
np.argmax(data, axis=0)

array([2, 1, 2], dtype=int64)

In [112]:
for i in data:
    print(i)

[1 2 3]
[7 5 2]
[10  1  8]
[6 3 4]


In [113]:
for a,b,c in data:
    print(a,b,c)

1 2 3
7 5 2
10 1 8
6 3 4
